# Generated by Django 5.2.6 on 2025-11-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='workouts_generated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
