# Generated by Django 5.2.6 on 2025-09-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='goal',
            field=models.CharField(choices=[('strength', 'Strength'), ('hypertrophy', 'Muscle Growth'), ('endurance', 'Endurance')], default='hypertrophy', max_length=20),
        ),
    ]
