# Generated by Django 5.2.6 on 2025-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_equipment_goal_remove_exercise_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroupCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('muscles', models.ManyToManyField(related_name='categories', to='workouts.musclegroup')),
            ],
        ),
    ]
