# Generated by Django 5.2.6 on 2025-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_musclegroupcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='mechanics',
            field=models.CharField(blank=True, choices=[('isolation', 'Isolation'), ('compound', 'Compound')], max_length=20),
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscle',
            field=models.ManyToManyField(related_name='primary_exercise', to='workouts.musclegroup'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(blank=True, related_name='secondary_exercise', to='workouts.musclegroup'),
        ),
    ]
