# Generated by Django 5.2.6 on 2025-09-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_exercise_muscles_exercise_mechanics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='primary_muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='secondary_muscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(related_name='exericses', to='workouts.musclegroup'),
        ),
    ]
