# Generated by Django 5.2.5 on 2025-09-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_remove_exercise_primary_muscle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='workouts.equipment'),
        ),
    ]
