# Generated by Django 5.2.5 on 2025-09-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_exercise_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='workouts.equipment'),
        ),
    ]
