# Generated by Django 5.2.6 on 2025-09-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_exercise_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscles',
        ),
        migrations.AddField(
            model_name='exercise',
            name='primary_muscle',
            field=models.ManyToManyField(blank=True, related_name='primary_exericses', to='workouts.musclegroup'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.ManyToManyField(blank=True, related_name='secondary_exercises', to='workouts.musclegroup'),
        ),
    ]
